
[is_progression_activate]
	#When false it will delete the progression lock of the mod (unbreakable ores blocks until [...], unusable tools etc...). Default = true
	is_progression_activate = true

[are_weapons_and_artifacts_drop_from_treasurebags]
	#When false this will disable the loot of weapons and artifacts from the treasure bags of every bosses! Default = true
	are_weapons_and_artifacts_drop_from_treasurebags = true

[is_hardmode_activate]
	#When false it will desactivate the harmode after beating the Ender Dragon (entities will have more health -> you can add your own entities with tags)  Default = true
	is_hardmode_activate = true

[hardmode_health_modifier]
	#This number increases the life of entities when entering hardmode troughout a multiplication. Default = 2.5 and don't forget the number and the dot
	hardmode_health_modifier = 2.5

[hardmode_damage_modifier]
	#This number increases the damages of entities when entering hardmode troughout a multiplication. Default = 2.0 and don't forget the number and the dot
	hardmode_damage_modifier = 2.0

